FOGL-3397 Added mandatory in asset name config
fledge-iot/fledge-south-csv pull request #1
Opened 2020-01-10 07:04 UTC by rajeshkumar426

Signed-off-by: rajeshkumar426 <rajeshkumar426@outlook.com>

2020-01-10 10:55 UTC, MarkRiddoch approved these changes

2020-02-13 12:33 UTC, ashish-jabble commented
@rajeshkumar426 Please resolve conflicts.

2020-02-13 12:55 UTC, ashish-jabble requested changes
fix wrong conflict resolution

2020-02-13 12:55 UTC, ashish-jabble commented on plugin.cpp
> +
No need of this define `CONFIG`, as we moved this to `default_config` as with latest develop.

2020-02-19 09:26 UTC, ashish-jabble approved these changes
Please do squash & merge

2020-02-20 09:13 UTC, merged